tuple = ( 'Ankit', 456 , 1.14, 'Patel', 70.2,True,False  )
tinytuple = (99, 'The Easylearn Academy')
print(tuple)
print(tinytuple)
print(tuple[0])
print(tuple[0:5])
print(tuple[0:5:2])
print(tuple[-1])
print(tuple + tinytuple)
print(tuple *3)
print(tuple.count('Patel'))
print(tuple.index('Patel'))